#!/bin/bash
set -e

INSTALLERS_DIR="$1"

WEB_INSTALLER=Xilinx_Unified_2022.2_1014_8888_Lin64

# main installer
rm -rf "$WEB_INSTALLER"
"$INSTALLERS_DIR/$WEB_INSTALLER.bin" --noexec --target "$WEB_INSTALLER"

# updaters
for UPDATER in Xilinx_Vivado_Vitis_Update_2022.2.1_1208_2036 Xilinx_Vivado_Vitis_Update_2022.2.2_0221_2201 ; do
    rm -rf "$UPDATER"
    "$INSTALLERS_DIR/$WEB_INSTALLER.bin" --noexec --target "$UPDATER"
    rm -rf "$UPDATER/data"
    tar xvzf "$INSTALLERS_DIR/$UPDATER.tar.gz" "$UPDATER/data"
done
