#! /usr/bin/env bash

export DISPLAY=:99
export RESOLUTION=1366x768x24

sudo /bin/rm -rf /tmp/.X11-unix
sudo /bin/rm -rf /tmp/.X99-lock
# sudo /bin/rm -f  /var/run/xrdp.pid

sudo /usr/bin/Xvfb ${DISPLAY}	\
	-screen 0 ${RESOLUTION} \
	-ac +extension GLX 	\
	+render -noreset &

sudo /usr/bin/x11vnc -xkb -noxrecord 	\
	-noxfixes -noxdamage 		\
	-display :99 -forever 		\
	-bg -nopw -rfbport 5900 &

startxfce4
	
