
CONFIG       += TDM
SAMPLE_RATE  := 48000
SAMPLE_WIDTH := 16
PREPROCESSOR_HLS := TRUE
PREPROCESSOR_I2S := FALSE
BD_TARGET    := $(BD_TDM)
I2S_SOURCE   := $(SOURCE_I2S_DIR)/i2s_transceiver_tdm.vhd
CONSTRAINT_FILE  := $(SOURCE_CONSTRAINTS_DIR)/zybo_tdm.xdc

$(call static_ok, - $(B)CONFIG_EXPERIMENTAL_TDM$(N) is $(B)ON$(N))
