// ********************************************************************
//                          IMPORTANT
// This is automatically generated by build.rs, do not change manually
// ********************************************************************


/// Bit 31 to 0 of ram_in
#[allow(dead_code)]
pub const AXI_LITE_RAM_IN_1: usize = 0x10;
/// Bit 63 to 32 of ram_in
#[allow(dead_code)]
pub const AXI_LITE_RAM_IN_2: usize = 0x14;
/// Bit 31 to 0 of ram_out
#[allow(dead_code)]
pub const AXI_LITE_RAM_OUT_1: usize = 0x1c;
/// Bit 63 to 32 of ram_out
#[allow(dead_code)]
pub const AXI_LITE_RAM_OUT_2: usize = 0x20;
/// Bit 31 to 0 of eth_ok
#[allow(dead_code)]
pub const AXI_LITE_ETH_OK: usize = 0x28;
/// Bit 31 to 0 of audio_in_len
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_LEN: usize = 0x30;
/// Bit 31 to 0 of audio_out_len
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_LEN: usize = 0x38;
/// Bit 31 to 0 of audio_in_channels
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_CHANNELS: usize = 0x40;
/// Control signal audio_in_channels_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_CHANNELS_CTRL: usize = 0x44;
/// Bit 31 to 0 of audio_out_channels
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_CHANNELS: usize = 0x50;
/// Control signal audio_out_channels_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_CHANNELS_CTRL: usize = 0x54;
/// Bit 31 to 0 of audio_in_r
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_R: usize = 0x60;
/// Control signal audio_in_r_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_R_CTRL: usize = 0x64;
/// Bit 31 to 0 of audio_in_w
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_W: usize = 0x70;
/// Control signal audio_in_w_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_IN_W_CTRL: usize = 0x74;
/// Bit 31 to 0 of audio_out_r
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_R: usize = 0x80;
/// Control signal audio_out_r_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_R_CTRL: usize = 0x84;
/// Bit 31 to 0 of audio_out_w
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_W: usize = 0x90;
/// Control signal audio_out_w_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_AUDIO_OUT_W_CTRL: usize = 0x94;
/// Bit 31 to 0 of status
#[allow(dead_code)]
pub const AXI_LITE_STATUS: usize = 0xa0;
/// Control signal status_ap_vld
#[allow(dead_code)]
pub const AXI_LITE_STATUS_CTRL: usize = 0xa4;
/// Bit 31 to 0 of read_clk
#[allow(dead_code)]
pub const AXI_LITE_READ_CLK: usize = 0xb0;
