 /****************************************************************************** 
 * @file ./ADAU1787Reg.c 
 * Autogenerated with sigmaS_to_syfala_generator.tcl. 
 * Registers configuration for ADAU1787.  
 * Based on X_IC_1_REG.h file, generated with Sigma Studio 
 * This file doesn't need to be regenerated each time. Only the header file configures the registers.
 * 
 * @authors M.POPOFF 
 * 
 * @date 11/17/2022 18:17:12 
 * 
 *****************************************************************************/ 
 


 #include <syfala/arm/iic_config.h> 
 #include <syfala/arm/ADAU1787Reg.h>
 #include <syfala/arm/utils.h>
 
 
 XStatus ADAU1787SetConfig()
 {
 	int Status; 

  Status = ADAU17XXRegWrite(REG_ADC_DAC_HP_PWR_IC_1_Sigma_ADDR+0x00, ((REG_ADC_DAC_HP_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_DAC_HP_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLL_MB_PGA_PWR_IC_1_Sigma_ADDR+0x00, ((REG_PLL_MB_PGA_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PLL_MB_PGA_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_PWR_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SAI_CLK_PWR_IC_1_Sigma_ADDR+0x00, ((REG_SAI_CLK_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SAI_CLK_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DSP_PWR_IC_1_Sigma_ADDR+0x00, ((REG_DSP_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DSP_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRC_PWR_IC_1_Sigma_ADDR+0x00, ((REG_ASRC_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRC_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_PWR_IC_1_Sigma_ADDR+0x00, ((REG_FINT_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_PWR_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_PWR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_PWR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_KEEPS_IC_1_Sigma_ADDR+0x00, ((REG_KEEPS_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_KEEPS_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_CLK_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_CLK_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_CLK_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL3_IC_1_Sigma_ADDR+0x01, ((REG_CLK_CTRL3_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL5_IC_1_Sigma_ADDR+0x00, ((REG_CLK_CTRL5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL5_IC_1_Sigma_ADDR+0x01, ((REG_CLK_CTRL5_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL7_IC_1_Sigma_ADDR+0x00, ((REG_CLK_CTRL7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL7_IC_1_Sigma_ADDR+0x01, ((REG_CLK_CTRL7_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLK_CTRL9_IC_1_Sigma_ADDR+0x00, ((REG_CLK_CTRL9_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_CLK_CTRL9_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_ADC_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_ADC_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_ADC_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_ADC_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CTRL5_IC_1_Sigma_ADDR+0x00, ((REG_ADC_CTRL5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_MUTES_IC_1_Sigma_ADDR+0x00, ((REG_ADC_MUTES_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC_MUTES_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC0_VOL_IC_1_Sigma_ADDR+0x00, ((REG_ADC0_VOL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC0_VOL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC1_VOL_IC_1_Sigma_ADDR+0x00, ((REG_ADC1_VOL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC1_VOL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC2_VOL_IC_1_Sigma_ADDR+0x00, ((REG_ADC2_VOL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC2_VOL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC3_VOL_IC_1_Sigma_ADDR+0x00, ((REG_ADC3_VOL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC3_VOL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA0_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_PGA0_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA0_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA0_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_PGA0_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA0_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA1_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_PGA1_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA1_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA1_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_PGA1_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA1_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA2_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_PGA2_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA2_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA2_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_PGA2_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA2_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA3_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_PGA3_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA3_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA3_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_PGA3_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA3_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_PGA_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PGA_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MBIAS_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_MBIAS_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MBIAS_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CTRL5_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CTRL5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CTRL6_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CTRL6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CTRL6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_MUTES_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_MUTES_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_MUTES_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL0_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL1_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL2_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL3_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL4_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL5_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL6_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_VOL7_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_VOL7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_VOL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_DAC_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DAC_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_DAC_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DAC_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_VOL0_IC_1_Sigma_ADDR+0x00, ((REG_DAC_VOL0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DAC_VOL0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_VOL1_IC_1_Sigma_ADDR+0x00, ((REG_DAC_VOL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DAC_VOL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_DAC_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DAC_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_DAC_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DAC_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_HP_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_HP_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_HP_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE2_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE3_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE4_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE5_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE6_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDEC_ROUTE7_IC_1_Sigma_ADDR+0x00, ((REG_FDEC_ROUTE7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDEC_ROUTE7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_FINT_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_FINT_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_FINT_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_FINT_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE2_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE3_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE4_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE5_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE6_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FINT_ROUTE7_IC_1_Sigma_ADDR+0x00, ((REG_FINT_ROUTE7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FINT_ROUTE7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCI_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_ASRCI_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCI_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCI_ROUTE01_IC_1_Sigma_ADDR+0x00, ((REG_ASRCI_ROUTE01_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCI_ROUTE01_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCI_ROUTE23_IC_1_Sigma_ADDR+0x00, ((REG_ASRCI_ROUTE23_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCI_ROUTE23_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_ASRCO_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCO_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_ASRCO_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCO_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_ASRCO_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCO_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_ROUTE2_IC_1_Sigma_ADDR+0x00, ((REG_ASRCO_ROUTE2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCO_ROUTE2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_ROUTE3_IC_1_Sigma_ADDR+0x00, ((REG_ASRCO_ROUTE3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ASRCO_ROUTE3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_RUN_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_RUN_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_RUN_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL5_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL5_IC_1_Sigma_ADDR+0x01, ((REG_FDSP_CTRL5_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL7_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_CTRL8_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_CTRL8_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_CTRL8_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_ADDR_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_ADDR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_ADDR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P0_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_P0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P0_IC_1_Sigma_ADDR+0x01, ((REG_FDSP_SL_P0_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P0_IC_1_Sigma_ADDR+0x02, ((REG_FDSP_SL_P0_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P0_IC_1_Sigma_ADDR+0x03, ((REG_FDSP_SL_P0_IC_1_Sigma_VALUE >> (8*3)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P1_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_P1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P1_IC_1_Sigma_ADDR+0x01, ((REG_FDSP_SL_P1_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P1_IC_1_Sigma_ADDR+0x02, ((REG_FDSP_SL_P1_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P1_IC_1_Sigma_ADDR+0x03, ((REG_FDSP_SL_P1_IC_1_Sigma_VALUE >> (8*3)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P2_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_P2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P2_IC_1_Sigma_ADDR+0x01, ((REG_FDSP_SL_P2_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P2_IC_1_Sigma_ADDR+0x02, ((REG_FDSP_SL_P2_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P2_IC_1_Sigma_ADDR+0x03, ((REG_FDSP_SL_P2_IC_1_Sigma_VALUE >> (8*3)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P3_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_P3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P3_IC_1_Sigma_ADDR+0x01, ((REG_FDSP_SL_P3_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P3_IC_1_Sigma_ADDR+0x02, ((REG_FDSP_SL_P3_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P3_IC_1_Sigma_ADDR+0x03, ((REG_FDSP_SL_P3_IC_1_Sigma_VALUE >> (8*3)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P4_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_P4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P4_IC_1_Sigma_ADDR+0x01, ((REG_FDSP_SL_P4_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P4_IC_1_Sigma_ADDR+0x02, ((REG_FDSP_SL_P4_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_P4_IC_1_Sigma_ADDR+0x03, ((REG_FDSP_SL_P4_IC_1_Sigma_VALUE >> (8*3)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_P4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_SL_UPDATE_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_SL_UPDATE_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_SL_UPDATE_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL4_IC_1_Sigma_ADDR+0x01, ((REG_SDSP_CTRL4_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL4_IC_1_Sigma_ADDR+0x02, ((REG_SDSP_CTRL4_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL7_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL7_IC_1_Sigma_ADDR+0x01, ((REG_SDSP_CTRL7_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL9_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL9_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL9_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL9_IC_1_Sigma_ADDR+0x01, ((REG_SDSP_CTRL9_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL9_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_CTRL11_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_CTRL11_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_CTRL11_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL3_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL4_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL5_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL6_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL7_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL8_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL8_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL8_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL9_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL9_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL9_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FSYNC0_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_FSYNC0_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FSYNC0_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_BCLK0_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_BCLK0_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_BCLK0_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDATAO0_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SDATAO0_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDATAO0_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDATAI0_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SDATAI0_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDATAI0_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FSYNC1_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_FSYNC1_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FSYNC1_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_BCLK1_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_BCLK1_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_BCLK1_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDATAO1_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SDATAO1_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDATAO1_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDATAI1_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SDATAI1_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDATAI1_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CLK0_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CLK0_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CLK0_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC_CLK1_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_DMIC_CLK1_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC_CLK1_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC01_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_DMIC01_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC01_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DMIC23_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_DMIC23_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DMIC23_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_I2C_SPI_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_I2C_SPI_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_I2C_SPI_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_IRQ_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ1_MASK1_IC_1_Sigma_ADDR+0x00, ((REG_IRQ1_MASK1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ1_MASK1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ1_MASK2_IC_1_Sigma_ADDR+0x00, ((REG_IRQ1_MASK2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ1_MASK2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ1_MASK3_IC_1_Sigma_ADDR+0x00, ((REG_IRQ1_MASK3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ1_MASK3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ2_MASK1_IC_1_Sigma_ADDR+0x00, ((REG_IRQ2_MASK1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ2_MASK1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ2_MASK2_IC_1_Sigma_ADDR+0x00, ((REG_IRQ2_MASK2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ2_MASK2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_IRQ2_MASK3_IC_1_Sigma_ADDR+0x00, ((REG_IRQ2_MASK3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_IRQ2_MASK3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_RESETS_IC_1_Sigma_ADDR+0x00, ((REG_RESETS_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_RESETS_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE2_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE3_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE4_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE5_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE6_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE7_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE8_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE8_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE8_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE9_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE9_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE9_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE10_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE10_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE10_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE11_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE11_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE11_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE12_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE12_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE12_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE13_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE13_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE13_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE14_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE14_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE14_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT0_ROUTE15_IC_1_Sigma_ADDR+0x00, ((REG_SPT0_ROUTE15_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT0_ROUTE15_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE2_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE3_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE3_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE3_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE4_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE4_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE4_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE5_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE5_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE5_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE6_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE6_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE6_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE7_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE7_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE7_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE8_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE8_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE8_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE9_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE9_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE9_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE10_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE10_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE10_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE11_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE11_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE11_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE12_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE12_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE12_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE13_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE13_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE13_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE14_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE14_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE14_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SPT1_ROUTE15_IC_1_Sigma_ADDR+0x00, ((REG_SPT1_ROUTE15_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SPT1_ROUTE15_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MP_CTRL10_IC_1_Sigma_ADDR+0x00, ((REG_MP_CTRL10_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MP_CTRL10_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SELFBOOT_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SELFBOOT_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SELFBOOT_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SW_EN_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SW_EN_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SW_EN_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_CTRL1_IC_1_Sigma_ADDR+0x00, ((REG_PDM_CTRL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PDM_CTRL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_CTRL2_IC_1_Sigma_ADDR+0x00, ((REG_PDM_CTRL2_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PDM_CTRL2_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_VOL0_IC_1_Sigma_ADDR+0x00, ((REG_PDM_VOL0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PDM_VOL0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_VOL1_IC_1_Sigma_ADDR+0x00, ((REG_PDM_VOL1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PDM_VOL1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_ROUTE0_IC_1_Sigma_ADDR+0x00, ((REG_PDM_ROUTE0_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PDM_ROUTE0_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_ROUTE1_IC_1_Sigma_ADDR+0x00, ((REG_PDM_ROUTE1_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PDM_ROUTE1_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_MEM_SPEED_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_MEM_SPEED_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_MEM_SPEED_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SDSP_MEM_SLEEP_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_SDSP_MEM_SLEEP_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_SDSP_MEM_SLEEP_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_MEM_SPEED_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_MEM_SPEED_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_MEM_SPEED_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_MEM_SLEEP_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_MEM_SLEEP_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_MEM_SLEEP_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_I2C_PAD_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_I2C_PAD_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_I2C_PAD_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_TEST_PAD0_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_TEST_PAD0_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_TEST_PAD0_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_TEST_PAD1_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_TEST_PAD1_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_TEST_PAD1_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC01_BIAS_OVERRIDE_IC_1_Sigma_ADDR+0x00, ((REG_ADC01_BIAS_OVERRIDE_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC01_BIAS_OVERRIDE_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC23_BIAS_OVERRIDE_IC_1_Sigma_ADDR+0x00, ((REG_ADC23_BIAS_OVERRIDE_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ADC23_BIAS_OVERRIDE_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_TEMP_ADC_BIAS_IC_1_Sigma_ADDR+0x00, ((REG_TEMP_ADC_BIAS_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_TEMP_ADC_BIAS_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MBIAS_TEST_IC_1_Sigma_ADDR+0x00, ((REG_MBIAS_TEST_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_MBIAS_TEST_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FDSP_TEST_MODES_IC_1_Sigma_ADDR+0x00, ((REG_FDSP_TEST_MODES_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FDSP_TEST_MODES_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FAULT_DISABLE_IC_1_Sigma_ADDR+0x00, ((REG_FAULT_DISABLE_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_FAULT_DISABLE_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ALDO_CTRL_IC_1_Sigma_ADDR+0x00, ((REG_ALDO_CTRL_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_ALDO_CTRL_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PMU_TEST_IC_1_Sigma_ADDR+0x00, ((REG_PMU_TEST_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PMU_TEST_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DUMMY_SPI_ENABLE_IC_1_Sigma_ADDR+0x00, ((REG_DUMMY_SPI_ENABLE_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_DUMMY_SPI_ENABLE_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLLCALCULATOR_IC_1_Sigma_ADDR+0x00, ((REG_PLLCALCULATOR_IC_1_Sigma_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PLLCALCULATOR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLLCALCULATOR_IC_1_Sigma_ADDR+0x01, ((REG_PLLCALCULATOR_IC_1_Sigma_VALUE >> (8*1)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PLLCALCULATOR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLLCALCULATOR_IC_1_Sigma_ADDR+0x02, ((REG_PLLCALCULATOR_IC_1_Sigma_VALUE >> (8*2)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PLLCALCULATOR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLLCALCULATOR_IC_1_Sigma_ADDR+0x03, ((REG_PLLCALCULATOR_IC_1_Sigma_VALUE >> (8*3)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1787]Error: could not write REG_PLLCALCULATOR_IC_1_Sigma\r\n"); 
 		return Status;
 	}


  return XST_SUCCESS; 
 }
 //End of file
