 /****************************************************************************** 
 * @file ./ADAU1777Reg.c 
 * Autogenerated with sigmaS_to_syfala_generator.tcl. 
 * Registers configuration for ADAU1777.  
 * Based on X_IC_1_REG.h file, generated with Sigma Studio 
 * This file doesn't need to be regenerated each time. Only the header file configures the registers.
 * 
 * @authors M.POPOFF 
 * 
 * @date 11/17/2022 18:17:11 
 * 
 *****************************************************************************/ 
 


 #include <syfala/arm/iic_config.h> 
 #include <syfala/arm/ADAU1777Reg.h>
 #include <syfala/arm/utils.h>
 
 
 XStatus ADAU1777SetConfig()
 {
 	int Status; 

  Status = ADAU17XXRegWrite(REG_CLK_CONTROL_IC_1_ADDR+0x00, ((REG_CLK_CONTROL_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_CLK_CONTROL_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLL_CTRL0_IC_1_ADDR+0x00, ((REG_PLL_CTRL0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PLL_CTRL0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLL_CTRL1_IC_1_ADDR+0x00, ((REG_PLL_CTRL1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PLL_CTRL1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLL_CTRL2_IC_1_ADDR+0x00, ((REG_PLL_CTRL2_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PLL_CTRL2_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLL_CTRL3_IC_1_ADDR+0x00, ((REG_PLL_CTRL3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PLL_CTRL3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PLL_CTRL4_IC_1_ADDR+0x00, ((REG_PLL_CTRL4_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PLL_CTRL4_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CLKOUT_SEL_IC_1_ADDR+0x00, ((REG_CLKOUT_SEL_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_CLKOUT_SEL_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_REGULATOR_IC_1_ADDR+0x00, ((REG_REGULATOR_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_REGULATOR_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CORE_CONTROL_IC_1_ADDR+0x00, ((REG_CORE_CONTROL_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_CORE_CONTROL_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SLEEP_INST_IC_1_ADDR+0x00, ((REG_SLEEP_INST_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SLEEP_INST_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CORE_ENABLE_IC_1_ADDR+0x00, ((REG_CORE_ENABLE_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_CORE_ENABLE_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CORE_IN_MUX_0_1_IC_1_ADDR+0x00, ((REG_CORE_IN_MUX_0_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_CORE_IN_MUX_0_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_CORE_IN_MUX_2_3_IC_1_ADDR+0x00, ((REG_CORE_IN_MUX_2_3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_CORE_IN_MUX_2_3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_SOURCE_0_1_IC_1_ADDR+0x00, ((REG_DAC_SOURCE_0_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DAC_SOURCE_0_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_SOURCE_0_1_IC_1_ADDR+0x00, ((REG_PDM_SOURCE_0_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PDM_SOURCE_0_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SOUT_SOURCE_0_1_IC_1_ADDR+0x00, ((REG_SOUT_SOURCE_0_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SOUT_SOURCE_0_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SOUT_SOURCE_2_3_IC_1_ADDR+0x00, ((REG_SOUT_SOURCE_2_3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SOUT_SOURCE_2_3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SOUT_SOURCE_4_5_IC_1_ADDR+0x00, ((REG_SOUT_SOURCE_4_5_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SOUT_SOURCE_4_5_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SOUT_SOURCE_6_7_IC_1_ADDR+0x00, ((REG_SOUT_SOURCE_6_7_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SOUT_SOURCE_6_7_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_SDATA_CH_IC_1_ADDR+0x00, ((REG_ADC_SDATA_CH_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC_SDATA_CH_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_SOURCE_0_1_IC_1_ADDR+0x00, ((REG_ASRCO_SOURCE_0_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ASRCO_SOURCE_0_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRCO_SOURCE_2_3_IC_1_ADDR+0x00, ((REG_ASRCO_SOURCE_2_3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ASRCO_SOURCE_2_3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ASRC_MODE_IC_1_ADDR+0x00, ((REG_ASRC_MODE_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ASRC_MODE_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CONTROL0_IC_1_ADDR+0x00, ((REG_ADC_CONTROL0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC_CONTROL0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CONTROL1_IC_1_ADDR+0x00, ((REG_ADC_CONTROL1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC_CONTROL1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CONTROL2_IC_1_ADDR+0x00, ((REG_ADC_CONTROL2_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC_CONTROL2_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_CONTROL3_IC_1_ADDR+0x00, ((REG_ADC_CONTROL3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC_CONTROL3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC0_VOLUME_IC_1_ADDR+0x00, ((REG_ADC0_VOLUME_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC0_VOLUME_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC1_VOLUME_IC_1_ADDR+0x00, ((REG_ADC1_VOLUME_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC1_VOLUME_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC2_VOLUME_IC_1_ADDR+0x00, ((REG_ADC2_VOLUME_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC2_VOLUME_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC3_VOLUME_IC_1_ADDR+0x00, ((REG_ADC3_VOLUME_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC3_VOLUME_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_CONTROL_0_IC_1_ADDR+0x00, ((REG_PGA_CONTROL_0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PGA_CONTROL_0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_CONTROL_1_IC_1_ADDR+0x00, ((REG_PGA_CONTROL_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PGA_CONTROL_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_CONTROL_2_IC_1_ADDR+0x00, ((REG_PGA_CONTROL_2_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PGA_CONTROL_2_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_CONTROL_3_IC_1_ADDR+0x00, ((REG_PGA_CONTROL_3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PGA_CONTROL_3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_STEP_CONTROL_IC_1_ADDR+0x00, ((REG_PGA_STEP_CONTROL_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PGA_STEP_CONTROL_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PGA_10DB_BOOST_IC_1_ADDR+0x00, ((REG_PGA_10DB_BOOST_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PGA_10DB_BOOST_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_POP_SUPPRESS_IC_1_ADDR+0x00, ((REG_POP_SUPPRESS_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_POP_SUPPRESS_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_TALKTHRU_IC_1_ADDR+0x00, ((REG_TALKTHRU_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_TALKTHRU_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_TALKTHRU_GAIN0_IC_1_ADDR+0x00, ((REG_TALKTHRU_GAIN0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_TALKTHRU_GAIN0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_TALKTHRU_GAIN1_IC_1_ADDR+0x00, ((REG_TALKTHRU_GAIN1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_TALKTHRU_GAIN1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MIC_BIAS_IC_1_ADDR+0x00, ((REG_MIC_BIAS_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MIC_BIAS_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_CONTROL1_IC_1_ADDR+0x00, ((REG_DAC_CONTROL1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DAC_CONTROL1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC0_VOLUME_IC_1_ADDR+0x00, ((REG_DAC0_VOLUME_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DAC0_VOLUME_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC1_VOLUME_IC_1_ADDR+0x00, ((REG_DAC1_VOLUME_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DAC1_VOLUME_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_OP_STAGE_MUTES_IC_1_ADDR+0x00, ((REG_OP_STAGE_MUTES_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_OP_STAGE_MUTES_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SAI_0_IC_1_ADDR+0x00, ((REG_SAI_0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SAI_0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SAI_1_IC_1_ADDR+0x00, ((REG_SAI_1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SAI_1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SOUT_CONTROL0_IC_1_ADDR+0x00, ((REG_SOUT_CONTROL0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SOUT_CONTROL0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_SOUT_CONTROL1_IC_1_ADDR+0x00, ((REG_SOUT_CONTROL1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_SOUT_CONTROL1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_OUT_IC_1_ADDR+0x00, ((REG_PDM_OUT_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PDM_OUT_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PDM_PATTERN_IC_1_ADDR+0x00, ((REG_PDM_PATTERN_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PDM_PATTERN_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP0_IC_1_ADDR+0x00, ((REG_MODE_MP0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP1_IC_1_ADDR+0x00, ((REG_MODE_MP1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP2_IC_1_ADDR+0x00, ((REG_MODE_MP2_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP2_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP3_IC_1_ADDR+0x00, ((REG_MODE_MP3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP4_IC_1_ADDR+0x00, ((REG_MODE_MP4_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP4_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP5_IC_1_ADDR+0x00, ((REG_MODE_MP5_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP5_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_MODE_MP6_IC_1_ADDR+0x00, ((REG_MODE_MP6_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_MODE_MP6_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PB_VOL_SET_IC_1_ADDR+0x00, ((REG_PB_VOL_SET_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PB_VOL_SET_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PB_VOL_CONV_IC_1_ADDR+0x00, ((REG_PB_VOL_CONV_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PB_VOL_CONV_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DEBOUNCE_MODE_IC_1_ADDR+0x00, ((REG_DEBOUNCE_MODE_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DEBOUNCE_MODE_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_RESERVED_IC_1_ADDR+0x00, ((REG_RESERVED_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_RESERVED_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_OP_STAGE_CTRL_IC_1_ADDR+0x00, ((REG_OP_STAGE_CTRL_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_OP_STAGE_CTRL_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DECIM_PWR_MODES_IC_1_ADDR+0x00, ((REG_DECIM_PWR_MODES_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DECIM_PWR_MODES_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_INTERP_PWR_MODES_IC_1_ADDR+0x00, ((REG_INTERP_PWR_MODES_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_INTERP_PWR_MODES_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_BIAS_CONTROL0_IC_1_ADDR+0x00, ((REG_BIAS_CONTROL0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_BIAS_CONTROL0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_BIAS_CONTROL1_IC_1_ADDR+0x00, ((REG_BIAS_CONTROL1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_BIAS_CONTROL1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PAD_CONTROL0_IC_1_ADDR+0x00, ((REG_PAD_CONTROL0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PAD_CONTROL0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PAD_CONTROL1_IC_1_ADDR+0x00, ((REG_PAD_CONTROL1_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PAD_CONTROL1_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PAD_CONTROL2_IC_1_ADDR+0x00, ((REG_PAD_CONTROL2_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PAD_CONTROL2_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PAD_CONTROL3_IC_1_ADDR+0x00, ((REG_PAD_CONTROL3_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PAD_CONTROL3_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PAD_CONTROL4_IC_1_ADDR+0x00, ((REG_PAD_CONTROL4_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PAD_CONTROL4_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_PAD_CONTROL5_IC_1_ADDR+0x00, ((REG_PAD_CONTROL5_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_PAD_CONTROL5_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_FAST_RATE_IC_1_ADDR+0x00, ((REG_FAST_RATE_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_FAST_RATE_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_DAC_CONTROL0_IC_1_ADDR+0x00, ((REG_DAC_CONTROL0_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_DAC_CONTROL0_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_VOL_BYPASS_IC_1_ADDR+0x00, ((REG_VOL_BYPASS_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_VOL_BYPASS_IC_1\r\n"); 
 		return Status;
 	}


  Status = ADAU17XXRegWrite(REG_ADC_OPER_IC_1_ADDR+0x00, ((REG_ADC_OPER_IC_1_VALUE >> (8*0)) & 0xFF),&Iic1);
  if (Status != XST_SUCCESS) {
 		if(Status == XST_FAILURE) PRINT_DEBUG(" >[ADAU1777]Error: could not write REG_ADC_OPER_IC_1\r\n"); 
 		return Status;
 	}


  return XST_SUCCESS; 
 }
 //End of file
